name: job-queue
version: 2.0.9
summary: Python-based queue for Rexroth ctrlX AUTOMATION platform 
title: job-queue
description: |
  job-queue provides functionality specific to the Rexroth mechatronics demo
base: core20
confinement: strict
grade: stable

architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s

parts:
  provider:
    plugin: python
    source: .

  datalayerdeb:
      plugin: dump
      source: ./deb/ctrlx-datalayer-1.7.13.deb
      source-type: deb
      stage-packages:
        - libzmq5

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
